alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ls='ls --color=auto'
alias ll='ls -l'
alias lm='ls -al |more'
alias root='sudo su -'
alias pfind='ps -aef | grep $@'
alias rd='rm -rf'
alias mkv3='mkvirtualenv -p /usr/bin/python3.3'
alias sub='sublime_text'
alias ssh='ssh -A'
alias gg='git gui &'
alias runps='sudo service postgresql start'
