# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Disable CTRL+S
stty -ixon

export LANG=en_US.utf8
export EDITOR=vim

# python virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/dev
source /usr/local/bin/virtualenvwrapper.sh

source $HOME/apps/resty/resty
source /usr/share/autojump/autojump.sh

PATH=$PATH:~/apps/p4merge/bin:/opt/sublime_text
export PATH

if [[ -f $HOME/.ssh/id_crt ]]; then
    eval `keychain --env /etc/profile.d/openssh.sh --eval --agents ssh id_rsa id_crt`
else
    eval `keychain --eval --agents ssh id_rsa`
fi

for file in $HOME/.bash/*.bash; do
    source $file
done
